/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sayyida Qurrata A'yunin (2210010331)
 */
public class AplikasiCekCuacaForm extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiCekCuacaForm
     */
    public AplikasiCekCuacaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        cbbKota = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCekCuaca = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        icoCuaca = new javax.swing.JLabel();
        btnAddFave = new javax.swing.JButton();
        lblCuaca = new javax.swing.JLabel();
        icoSuhu = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblAngin = new javax.swing.JLabel();
        icoAngin = new javax.swing.JLabel();
        lblKota = new javax.swing.JLabel();
        Hapus1 = new javax.swing.JButton();
        btnBersih1 = new javax.swing.JButton();
        lblKota1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Aplikasi Cek Cuaca Sederhana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTextField1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        cbbKota.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbbKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Pilih kota)", "Martapura", "Banjarmasin" }));
        cbbKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKotaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Kondisi Cuaca Sekarang");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Ketik Kota yang ingin di cek");

        btnCekCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnCekCuaca.setText("Cek Cuaca");

        btnSimpan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan Data");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Pilih kota yang tersimpan");

        icoCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoCuaca.setText("Gambar Cuaca");

        btnAddFave.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnAddFave.setText("Simpan Ke Favorit");

        lblCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblCuaca.setText("Desc. Weather");

        icoSuhu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoSuhu.setText("Suhu Icon");

        lblSuhu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblSuhu.setText("Suhu Desc.");

        lblAngin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblAngin.setText("Kecepatan Angin dan kelembapan");

        icoAngin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoAngin.setText("Angin Icon");

        lblKota.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblKota.setText("Nama Kota Muncul Disini!");

        Hapus1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Hapus1.setText("Hapus");

        btnBersih1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnBersih1.setText("Bersihkan");

        lblKota1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblKota1.setText("Pilih atau Cari Nama Kota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(icoCuaca)
                    .addComponent(lblCuaca)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(icoSuhu)
                        .addGap(18, 18, 18)
                        .addComponent(lblSuhu))
                    .addComponent(lblAngin)
                    .addComponent(icoAngin)
                    .addComponent(lblKota))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCekCuaca)
                                .addGap(18, 18, 18)
                                .addComponent(btnBersih1)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddFave)
                                .addContainerGap(54, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1)
                                            .addComponent(cbbKota, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel4))))
                                    .addComponent(lblKota1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hapus1)
                        .addGap(29, 29, 29)
                        .addComponent(btnSimpan)
                        .addGap(141, 141, 141))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblKota1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCekCuaca)
                            .addComponent(btnAddFave)
                            .addComponent(btnBersih1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hapus1)
                            .addComponent(btnSimpan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(icoCuaca)
                        .addGap(11, 11, 11)
                        .addComponent(lblCuaca)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuhu)
                            .addComponent(icoSuhu))
                        .addGap(18, 18, 18)
                        .addComponent(icoAngin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAngin)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jSeparator1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbKotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuacaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus1;
    private javax.swing.JButton btnAddFave;
    private javax.swing.JButton btnBersih1;
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbbKota;
    private javax.swing.JLabel icoAngin;
    private javax.swing.JLabel icoCuaca;
    private javax.swing.JLabel icoSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAngin;
    private javax.swing.JLabel lblCuaca;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblKota1;
    private javax.swing.JLabel lblSuhu;
    // End of variables declaration//GEN-END:variables
}
