/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author Sayyida Qurrata A'yunin (2210010331)
 */
public class AplikasiCekCuacaForm extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiCekCuacaForm
     */
    public AplikasiCekCuacaForm() {
        initComponents();
    }
private String getWeatherData(String kotaNama) {
    String apiKey = "589e7fc60fe84ccb9be01d4c426455e1"; // API Key Saya
    String apiUrl = "http://api.openweathermap.org/data/2.5/weather?q=" + kotaNama + "&appid=" + apiKey + "&units=metric";
    StringBuilder response = new StringBuilder();
    
    try {
        URL url = new URL(apiUrl);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                response.append(line);
            }
        }
        conn.disconnect();
    } catch (IOException e) {
    }
    
    return response.toString();
}

private void displayWeather(String kotaNama) {
    try {
        String jsonData = getWeatherData(kotaNama);
        if (jsonData != null && !jsonData.isEmpty()) {
            JSONObject jsonObject = new JSONObject(jsonData);
            
            // Extract weather information
            String city = jsonObject.getString("name");
            double temp = jsonObject.getJSONObject("main").getDouble("temp");
            int humidity = jsonObject.getJSONObject("main").getInt("humidity"); // Extract humidity
            String description = jsonObject.getJSONArray("weather").getJSONObject(0).getString("description");
            String iconCode = jsonObject.getJSONArray("weather").getJSONObject(0).getString("icon");
            double windSpeed = jsonObject.getJSONObject("wind").getDouble("speed");
            
            // Update GUI components
            lblCuaca.setText(city + ": " + description);
            lblSuhu.setText("Temperature: " + temp + "°C");
            lblAngin.setText("Wind Speed: " + windSpeed + " m/s");
            lblKelembapan.setText("Kelembapan: " + humidity + " %");
            
            // Fetch and set the weather icon
            String iconUrl = "http://openweathermap.org/img/wn/" + iconCode + ".png";
            URL url = new URL(iconUrl);
            ImageIcon icon = new ImageIcon(url);
            icoCuaca.setIcon(new ImageIcon(icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        } else {
            lblCuaca.setText("Error fetching data");
            lblSuhu.setText("");
            lblAngin.setText("");
            icoCuaca.setIcon(null);
        }
    } catch (MalformedURLException | JSONException e) {
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtKota = new javax.swing.JTextField();
        cbbKota = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCekCuaca = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        icoCuaca = new javax.swing.JLabel();
        btnAddFave = new javax.swing.JButton();
        lblCuaca = new javax.swing.JLabel();
        icoSuhu = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblAngin = new javax.swing.JLabel();
        icoAngin = new javax.swing.JLabel();
        lblKota = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnBersih1 = new javax.swing.JButton();
        lblKota1 = new javax.swing.JLabel();
        lblKelembapan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Aplikasi Cek Cuaca Sederhana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtKota.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        cbbKota.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbbKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Pilih kota)", "Martapura", "Banjarmasin" }));
        cbbKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKotaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Kondisi Cuaca Sekarang");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Ketik Kota yang ingin di cek");

        btnCekCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnCekCuaca.setText("Cek Cuaca");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan Data");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Pilih kota yang tersimpan");

        icoCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoCuaca.setText("Gambar Cuaca");

        btnAddFave.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnAddFave.setText("Simpan Ke Favorit");
        btnAddFave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFaveActionPerformed(evt);
            }
        });

        lblCuaca.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblCuaca.setText("Desc. Weather");

        icoSuhu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoSuhu.setText("Suhu Icon");

        lblSuhu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblSuhu.setText("Suhu Desc.");

        lblAngin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblAngin.setText("Kecepatan Angin");

        icoAngin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        icoAngin.setText("Angin Icon");

        lblKota.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblKota.setText("Nama Kota Muncul Disini!");

        btnHapus.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");

        btnBersih1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnBersih1.setText("Bersihkan");
        btnBersih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersih1ActionPerformed(evt);
            }
        });

        lblKota1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblKota1.setText("Pilih atau Cari Nama Kota");

        lblKelembapan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblKelembapan.setText("Kelembapan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(icoCuaca)
                            .addComponent(lblCuaca)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(icoSuhu)
                                .addGap(18, 18, 18)
                                .addComponent(lblSuhu))
                            .addComponent(icoAngin)
                            .addComponent(lblKota))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCekCuaca)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBersih1)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddFave)
                                        .addContainerGap(60, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtKota)
                                                    .addComponent(cbbKota, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel4))))
                                            .addComponent(lblKota1))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus)
                                .addGap(29, 29, 29)
                                .addComponent(btnSimpan)
                                .addGap(141, 141, 141))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAngin)
                        .addGap(18, 18, 18)
                        .addComponent(lblKelembapan)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblKota1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCekCuaca)
                            .addComponent(btnAddFave)
                            .addComponent(btnBersih1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnSimpan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(icoCuaca)
                        .addGap(11, 11, 11)
                        .addComponent(lblCuaca)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuhu)
                            .addComponent(icoSuhu))
                        .addGap(18, 18, 18)
                        .addComponent(icoAngin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAngin)
                    .addComponent(lblKelembapan))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jSeparator1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbKotaActionPerformed

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
          // Get selected city or manual input
    String pilihKota = cbbKota.getSelectedItem().toString();
    String inputKota = txtKota.getText().trim();
    String kotaNama = !inputKota.isEmpty() ? inputKota : pilihKota;
    
    // Display weather for the city
    displayWeather(kotaNama);
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnBersih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersih1ActionPerformed
    txtKota.setText("");
    lblCuaca.setText("");
    lblSuhu.setText("");
    lblAngin.setText("");
    lblKelembapan.setText("");
    icoCuaca.setIcon(null);
    }//GEN-LAST:event_btnBersih1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // File chooser to select save location
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Data Cuaca");
    
    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileToSave))) {
            // Writing data in CSV format
            writer.println("Keterangan Cuaca, Temperatur, Kelembapan, Kecepatan Angin");
            writer.printf("%s, %s, %s, %s\n", 
                lblCuaca.getText(),
                lblSuhu.getText(),
                lblAngin.getText(),
                lblKelembapan.getText()
            );
            JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnAddFaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFaveActionPerformed
        String kotaNama = txtKota.getText().trim();
    
    // Check if city name is empty
    if (kotaNama.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama kota tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Add city to combo box
    cbbKota.addItem(kotaNama);
    JOptionPane.showMessageDialog(this, "Kota berhasil ditambahkan ke favorit!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    
    // Clear the text field
    txtKota.setText("");
    }//GEN-LAST:event_btnAddFaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuacaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFave;
    private javax.swing.JButton btnBersih1;
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbbKota;
    private javax.swing.JLabel icoAngin;
    private javax.swing.JLabel icoCuaca;
    private javax.swing.JLabel icoSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAngin;
    private javax.swing.JLabel lblCuaca;
    private javax.swing.JLabel lblKelembapan;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblKota1;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
